name: CI  

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  build-and-lint:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.11'  

      - name: Install backend deps  
        run: |  
          python -m pip install --upgrade pip  
          pip install fastapi uvicorn sqlalchemy aiosqlite  

      - name: Set up Node  
        uses: actions/setup-node@v4  
        with:  
          node-version: '18'  

      - name: Install frontend deps  
        run: |  
          cd frontend  
          npm ci  

      - name: Build frontend  
        run: |  
          cd frontend  
          npm run build  

      - name: Lint backend (optional)  
        run: |  
          if command -v flake8 >/dev/null 2>&1; then flake8 || true; fi  

      - name
